### ISSUE TITLE
News: News post doesn't limit to 5 lines

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Daytone-Printing#54]
![image](https://cloud.githubusercontent.com/assets/13363508/9677142/e654712a-5308-11e5-9a62-2333ef279088.png)

**Comment by maehtitan** [comment]
I see 4 lines of text

![image](https://cloud.githubusercontent.com/assets/13363508/9781549/366752c2-57c8-11e5-9dd7-a683377d72ad.png)

**Comment by christiancebudigital** [comment]
Hi Maeh,

i think this is correct since, there is no featured image on the post and we cannot also control the words beeing used in the site, and what i mean limit is max 5 lines, so 1-4 is still acceptable, let me know your thoughts on this regards.

Thanks,
Christian

**Comment by maehtitan** [comment]
Pls refer to this fixed bug: https://github.com/titan-cebu/Dynamic-Group/issues/23
