### ISSUE TITLE
Footer Section - General: Missing above padding which resulted to the titan logo overlapped the map above except for Homepage and Contact page

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Daytone-Printing#6]
![image](https://cloud.githubusercontent.com/assets/13363508/9624511/438a9840-5180-11e5-9d08-f6d86f1d32ab.png)

**Comment by maehtitan** [comment]
Not yet fixed in News Single page in mobile view
Devices:
S4 (portrait & landscape)
Itouch (portrait & landscape)
![image](https://cloud.githubusercontent.com/assets/13363508/9784626/e131b682-57de-11e5-8b7e-5b0a3c5e62a6.png)

**Comment by christiancebudigital** [comment]
Hi Maeh,

Working on our end, but we cant replicate, since we dont have ipod, please clear cache.

Thanks,
Christian

**Comment by maehtitan** [comment]
<b>Still not fixed, same issues above in both devices.</b>

**Comment by maehtitan** [comment]
<b>Issues still recurring in IE11 or IE Edge</b>

**Comment by maehtitan** [comment]
<h5>Issue not yet fixed in the following pages link below:
http://daytoneprinting.stage.titanweb.com.au/privacy-policy/
http://daytoneprinting.stage.titanweb.com.au/testimonials/
http://daytoneprinting.stage.titanweb.com.au/thank-you/
http://daytoneprinting.stage.titanweb.com.au/who-we-are/
http://daytoneprinting.stage.titanweb.com.au/faq/
http://daytoneprinting.stage.titanweb.com.au/gallery/
http://daytoneprinting.stage.titanweb.com.au/news/
http://daytoneprinting.stage.titanweb.com.au/news/news-4/
http://daytoneprinting.stage.titanweb.com.au/services/

<h5> Fixed on the following pages below:
Homepage - http://daytoneprinting.stage.titanweb.com.au/
Services Single - http://daytoneprinting.stage.titanweb.com.au/service-category/test-category/?param=test-category
Services Sub - http://daytoneprinting.stage.titanweb.com.au/posts-services/test-services/?param=test-category

**Comment by maehtitan** [comment]
Still not fixed in News Single View

**Comment by maehtitan** [comment]
Already fixed in mobile view but Still not fixed in News Single View desktop view

**Comment by maehtitan** [comment]
Recurring Issue in Desktop View: Services Sub View page
![image](https://cloud.githubusercontent.com/assets/13363508/10184034/6ebfb9a6-6769-11e5-8fbb-ac314322b59d.png)

Recurring Issue in Ipad: Who We Are, Sitemap,Services & Services Single View, News & News Single View, Services & Services Sub View, Thank You, Testimonials, Privacy Policy, Gallery, FAQ

Recurring Issue in S4 & Itouch: Services Sub View

**Comment by maehtitan** [comment]
Hi @christiancebudigital,

Recurring Issue in Desktop View: Services Sub View page
-Fixed

Recurring Issue in Ipad: Who We Are, Sitemap, Services & Services Single View, News & News Single View, Services & Services Sub View, Thank You, Testimonials, Privacy Policy, Gallery, FAQ
-Not all are fixed. Fixed only in Services Single View and Sub View the rest of the pages mentioned above are not yet fixed

Recurring Issue in S4 & Itouch: Services Sub View
-Fixed

Thanks

**Comment by maehtitan** [comment]
Hi @christiancebudigital, 

Fixed in Ipad but only 1 issue recurring in Itouch and S4 News Single View. Please fix and hoping that no other device or browser views will be affected.

![image](https://cloud.githubusercontent.com/assets/13363508/10240625/fbd126d8-6910-11e5-9aa3-4c0cef40d337.png)

Thanks
