### ISSUE TITLE
Homepage - Prefooter: Labels header in Opera and Chrome has different rendered font from the rest of the browser in 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Daytone-Printing#62]
![image](https://cloud.githubusercontent.com/assets/13363508/9678276/e67b3776-5315-11e5-81f7-c014c766ed0b.png)

**Comment by christiancebudigital** [comment]
Hi Maeh,

please clear cache, it is working well on our end, ive attached here the screenshot.
![maps](https://cloud.githubusercontent.com/assets/11186331/9725867/11d8f296-561d-11e5-8045-c12d4cf8dba4.jpg)


Cheers,
Christian

**Comment by maehtitan** [comment]
Hi @christiancebudigital 

Sorry it's the problem of my PC

Thanks
