### ISSUE TITLE
Footer - Section - Inner Pages: Contact layout is not the same from the homepage alignment and the design provided

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Daytone-Printing#64]
![image](https://cloud.githubusercontent.com/assets/13363508/9679060/bd9185b0-531d-11e5-9ce6-5875c0b2f8bf.png)

**Comment by maehtitan** [comment]
Please apply fixes also in Ipad view Inner Parent pages

**Comment by christiancebudigital** [comment]
Hi Maeh,

Please clear your cache as this is working on our end.

Thanks,
Christian

**Comment by maehtitan** [comment]
Sorry but Issues still not fixed

**Comment by maehtitan** [comment]
<b>All are fixed in mobile view but Issues recurring to all browsers in all pages except for Homepage, Services Single view and Sub View</b>

**Comment by maehtitan** [comment]
<h5>Issue not yet fixed in the following pages link below:
http://daytoneprinting.stage.titanweb.com.au/privacy-policy/
http://daytoneprinting.stage.titanweb.com.au/testimonials/
http://daytoneprinting.stage.titanweb.com.au/thank-you/
http://daytoneprinting.stage.titanweb.com.au/who-we-are/
http://daytoneprinting.stage.titanweb.com.au/faq/
http://daytoneprinting.stage.titanweb.com.au/gallery/
http://daytoneprinting.stage.titanweb.com.au/news/
http://daytoneprinting.stage.titanweb.com.au/news/news-4/
http://daytoneprinting.stage.titanweb.com.au/services/

<h5> Fixed on the following pages below:
Homepage - http://daytoneprinting.stage.titanweb.com.au/
Services Single - http://daytoneprinting.stage.titanweb.com.au/service-category/test-category/?param=test-category
Services Sub - http://daytoneprinting.stage.titanweb.com.au/posts-services/test-services/?param=test-category

**Comment by maehtitan** [comment]
Not yet fixed in News Single View

**Comment by maehtitan** [comment]
Already fixed in mobile view but Still not fixed in News Single View desktop view

**Comment by christiancebudigital** [comment]
Hi Maeh,

This is fixed on or end, see attached screenshot.

![news](https://cloud.githubusercontent.com/assets/11186331/10156321/68d8c81e-66b2-11e5-85d4-7ef280b09ef0.jpg)

Thanks,
Christian
