### ISSUE TITLE
Homepage - Ipad: To occupy the whole width of the screen in landscape view and to prevent to show the white spaces both ends, best to make the container as 50% and float it to left 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Daytone-Printing#65]
Device:
Ipad (landscape)
![image](https://cloud.githubusercontent.com/assets/13363508/9679308/0f27f9de-5320-11e5-94e8-2627377bbe10.png)

**Comment by maehtitan** [comment]
<b>It looks like this in portrait view</b>
![image](https://cloud.githubusercontent.com/assets/13363508/9782098/014f0bde-57cd-11e5-9cc3-70490818de8c.png)
<b>white gap spaces are visible</b>

**Comment by christiancebudigital** [comment]
Hi Maeh,

please clear cache, as this is working on our end.

Thanks,
Christian

**Comment by maehtitan** [comment]
<b>After clearing cache no changes has been made still recurring just like the image above on iPad (portrait)</b>
