### ISSUE TITLE
Homepage - Mobile: Services Category text together with the button arrow are not vertically centered

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Daytone-Printing#66]
Devices
Itouch (portrait)
S4 (portrait)
![image](https://cloud.githubusercontent.com/assets/13363508/9679561/22738506-5322-11e5-9247-0e47cfe3edeb.png)

**Comment by maehtitan** [comment]
It looks like this currently.
![image](https://cloud.githubusercontent.com/assets/13363508/9782449/bf413368-57cf-11e5-86c0-899de0b78eb4.png)

**Comment by maehtitan** [comment]
<b>Fixed in S4 but not in Itouch</b>

![image](https://cloud.githubusercontent.com/assets/13363508/9782475/f66090b4-57cf-11e5-90df-0a66c1e2ad3e.png)

**Comment by christiancebudigital** [comment]
Hi Maeh,

Let me know if it is still displaying the issue, as it is already working in our end.

Thanks,
Christian

**Comment by maehtitan** [comment]
Issue still recurring the same on the images above
