### ISSUE TITLE
General Pages- Mobile: Content area are center aligned to all pages which is left-aligned by default in desktop view.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Daytone-Printing#67]
Devices:
Ipad (portrait)
Itouch (portrait & landscape)
S4 (portrait & landscape)

![image](https://cloud.githubusercontent.com/assets/13363508/9679582/60e2354e-5322-11e5-94d7-ee4b0509fa6a.png)

**Comment by maehtitan** [comment]
<b>Please include the Page title just like the left aligned Page title in Desktop view</b>

**Comment by christiancebudigital** [comment]
Hi Maeh, 

Im really confused on your statments, please clarify this one out, so we can sort this one out. homepage content, innerpages content and mobile content.

Thanks,
Christian

**Comment by maehtitan** [comment]
@christiancebudigital 

<b>General Pages (Mobile) - The page titles header <H1> are center aligned currently, please have it left align just like the desktop view.</b>

<b>Regarding, the homepage, as I was confused, It was center aligned by design but it looks good to make it as is the left alignments since there are unordered list of the contents, So where to follow? The current implemented one you made, or the design?</b>
![image](https://cloud.githubusercontent.com/assets/13363508/9984660/84db8782-604e-11e5-8835-612ad0a5bf4a.png)

**Comment by christiancebudigital** [comment]
Hi Maeh,

I think we will follow the design, since, this is the approved design by the client, let me know your thoughts :D

Thanks,
Christian

**Comment by maehtitan** [comment]
@christiancebudigital Yes I'm fine by followin the design but please have it styled properly the unordered list. Thanks

**Comment by maehtitan** [comment]
Will make a separate ticket regarding this <b>"General Pages (Mobile) - The page titles header are center aligned currently, please have it left align just like the desktop view." </b>

**Comment by maehtitan** [comment]
The homepage still left aligned in desktop and in mobile view, you mentioned above that we should follow the design but still left align
![image](https://cloud.githubusercontent.com/assets/13363508/10040016/7096df16-620a-11e5-9ce6-ebddaead4f24.png)

**Comment by maehtitan** [comment]
Homepage still left aligned, design was center align

**Comment by maehtitan** [comment]
<b> No changes has been made
![image](https://cloud.githubusercontent.com/assets/13363508/10154375/15529774-6699-11e5-9547-25bb92fba3fe.png)

**Comment by maehtitan** [comment]
![image](https://cloud.githubusercontent.com/assets/13363508/10156445/ac0a8450-66b3-11e5-8ab3-3419c291db56.png)

**Comment by christiancebudigital** [comment]
Hi Maeh, 

See attached file, this is working on our end.
![working](https://cloud.githubusercontent.com/assets/11186331/10183452/82d9edf0-6762-11e5-9232-c9953dd923bb.jpg)

Thanks,
Christian

**Comment by maehtitan** [comment]
Hi @christiancebudigital,

Yes, It was center but I have stated above that please make sure you style properly the unoredered list 
![image](https://cloud.githubusercontent.com/assets/13363508/10183710/4bcad09c-6765-11e5-9ea6-ab34c8749314.png)

just like the sample site I have given 9 days ago : http://stechgroup.stage.titanweb.com.au/
