### ISSUE TITLE
Services - Single View and Sub View - Mobile: Please fit the width image to its header Completed Jobs layout so that it won't look like being cut 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Daytone-Printing#83]
![image](https://cloud.githubusercontent.com/assets/13363508/9986261/14c6127c-606d-11e5-9c55-dbf0c3af0c44.png)

**Comment by maehtitan** [comment]
Width still too small doesn't vertically align with the above header background layout

**Comment by maehtitan** [comment]
Might as well center align the header coz it looks like this at the moment,
![image](https://cloud.githubusercontent.com/assets/13363508/10042122/fbcbf10a-621b-11e5-83e1-e1f289da23c8.png)

**Comment by maehtitan** [comment]
No changes has been made

**Comment by maehtitan** [comment]
Not yet fixed in S4 (portrait & landscape)

**Comment by christiancebudigital** [comment]
Hi Maeh,

Please clear your cache, this is working on our end.

Thanks,
Christian
